modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="ravageandcabbage" #mandatory
version="1.2.3" #mandatory
displayName="Ravage & Cabbage" #mandatory
credits="Vaky, Ninni" #optional
authors="Superlord, codyhuh" #optional
description='''A fun mod adding cabbages and expanding ravagers!'''
[[dependencies.ravageandcabbage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
