modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="ravageandcabbage" #mandatory
version="1.1.1" #mandatory
displayName="Ravage & Cabbage" #mandatory
credits="Superlord, Coda, Ninni, Larry" #optional
authors="Team Draco" #optional
description='''A fun mod adding cabbages and expanding ravagers!'''
[[dependencies.ravageandcabbage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
